name: jobs_tdd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  logger: ^1.1.0
  mockito: ^5.1.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  injectable: ^1.5.3
  file_picker: ^4.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  